[package]
name = "api"
version = "0.1.0"
authors = ["Tim Anderegg <timothy.anderegg@gmail.com>"]

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"
rand = "0.5.5"
reqwest = "0.8.6"
xml-rs = "0.7.0"
serde_derive = "*"
serde = "*"
serde-xml-rs = "*"
